### ISSUE TITLE
Unable to Download from Development Branch

### ISSUE THREAD

**Issue by DroidFreak32** [RemixDev/DRemixIssues#157]
**Describe the bug**
Trying to download from the development branch leads to the following error:

```
[Error] [Avenged Sevenfold - Breaking Their Hold] Decryption error: TypeError: Cannot read property 'join' of undefined
[Error] [Avenged Sevenfold - Breaking Their Hold] Error: TypeError: Cannot read property 'join' of undefined
[Info] Now downloading: Avenged Sevenfold - Thick And Thin
[Info] [Avenged Sevenfold - Thick And Thin] Getting BPM
[Error] TypeError: Cannot read property 'join' of undefined
    at getMetadata (/home/user/oss_stuff/deezloaderremix/app/app.js:2928:59)
    at IncomingMessage.<anonymous> (/home/user/oss_stuff/deezloaderremix/app/app.js:2316:46)
    at IncomingMessage.emit (events.js:209:13)
    at emitReadable_ (_stream_readable.js:570:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[Info] [Avenged Sevenfold - Thick And Thin] Is track explicit? Checking now
[Info] [Avenged Sevenfold - Thick And Thin] Downloading file to /home/user/Music/Deezloader/Avenged Sevenfold/2002 - Sounding The Seventh Trumpet/Avenged Sevenfold - Thick And Thin.flac
[Info] [Avenged Sevenfold - Thick And Thin] Cover already downloaded
[Info] [Avenged Sevenfold - Thick And Thin] Starting the download process
[Error] TypeError: Cannot read property 'join' of undefined
    at getMetadata (/home/user/oss_stuff/deezloaderremix/app/app.js:2928:59)
    at IncomingMessage.<anonymous> (/home/user/oss_stuff/deezloaderremix/app/app.js:2316:46)
    at IncomingMessage.emit (events.js:209:13)
    at emitReadable_ (_stream_readable.js:570:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**To Reproduce**
1. Go to 'Latest Development Branch > Start Deezloader > Search for Artist > Download entire album'
2. See error

**Expected behavior**
Songs get downloaded properly

**Screenshots**
N/A - Log Given

**Desktop (please complete the following information):**
 - OS: Linux
 - Version Ubuntu 18.04
 - Did you build it from the repo?: Yes
 - If so which branch?: Development

**Log File**
```
[Error] [Avenged Sevenfold - Breaking Their Hold] Decryption error: TypeError: Cannot read property 'join' of undefined
[Error] [Avenged Sevenfold - Breaking Their Hold] Error: TypeError: Cannot read property 'join' of undefined
[Info] Now downloading: Avenged Sevenfold - Thick And Thin
[Info] [Avenged Sevenfold - Thick And Thin] Getting BPM
[Error] TypeError: Cannot read property 'join' of undefined
    at getMetadata (/home/user/oss_stuff/deezloaderremix/app/app.js:2928:59)
    at IncomingMessage.<anonymous> (/home/user/oss_stuff/deezloaderremix/app/app.js:2316:46)
    at IncomingMessage.emit (events.js:209:13)
    at emitReadable_ (_stream_readable.js:570:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[Info] [Avenged Sevenfold - Thick And Thin] Is track explicit? Checking now
[Info] [Avenged Sevenfold - Thick And Thin] Downloading file to /home/user/Music/Deezloader/Avenged Sevenfold/2002 - Sounding The Seventh Trumpet/Avenged Sevenfold - Thick And Thin.flac
[Info] [Avenged Sevenfold - Thick And Thin] Cover already downloaded
[Info] [Avenged Sevenfold - Thick And Thin] Starting the download process
[Error] TypeError: Cannot read property 'join' of undefined
    at getMetadata (/home/user/oss_stuff/deezloaderremix/app/app.js:2928:59)
    at IncomingMessage.<anonymous> (/home/user/oss_stuff/deezloaderremix/app/app.js:2316:46)
    at IncomingMessage.emit (events.js:209:13)
    at emitReadable_ (_stream_readable.js:570:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Possible Implementation**
Revert Commit f48404a4c572aae6dc7c837df6dab8650db9f45d

**Additional context**
Album in Question - Sounding The Seventh Trumpet by Avenged Sevenfold

**Comment by RemixDev** [comment]
I can't recreate this issue

**Comment by RemixDev** [comment]
Send me your config.json so I can check it with your settings

**Comment by RemixDev** [comment]
Also try doing a clean install
use ./clean.sh and then redo npm install

**Comment by DroidFreak32** [comment]
`clean.sh` did the trick!

Thanks!
