### ISSUE TITLE
Error: ENOTDIR: not a directory, during build Linux

### ISSUE THREAD

**Issue by axeII** [RemixDev/DRemixIssues#27]
**Describe the bug**
During the build I am having error for making directory `/root/.config/Deezloader\ Remix/logs

**To Reproduce**
Steps to reproduce the behaviour:
1. Git clone this repo https://github.com/Bockiii/deezloadermx-docker
2. docker build  bocki/deezloaderrmx -t . 
3. docker run -d --name Deezldr \
              -v /your/storage/path/:/downloads \
              -v /your/config/location:/config \
              -p 1730:1730 \
              bocki/deezloaderrmx

**Expected behaviour**
Installation would not fail.

**Desktop (please complete the following information):**
 - OS: Linux debian stretch arm64v8
 - Version: latest
 - Did you build it from the repo?: Yes builded with latest node
 - If so which branch?: master and development

**Log File**
```bash
/deezloaderremix/app/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:45
        throw err0
        ^

Error: ENOTDIR: not a directory, mkdir '/root/.config/Deezloader Remix/logs'
    at Object.mkdirSync (fs.js:764:3)
    at Object.mkdirsSync (/deezloaderremix/app/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
    at Object.<anonymous> (/deezloaderremix/app/utils/logger.js:7:4)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/deezloaderremix/app/app.js:28:16)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -20,
  syscall: 'mkdir',
  code: 'ENOTDIR',
  path: '/root/.config/Deezloader Remix/logs'
}
```

**Possible Implementation**
During the build when I checked directory `/root/.config/Deezloader\ Remix it's just file not directory which is open during the installation (I can't remove it).

**Comment by RemixDev** [comment]
That's not my script

Looking at the code it seems it's using yarn
Try using npm instead

**Comment by axeII** [comment]
Npm did help.. sort of. But then I had different error with missing packages. In the end I wasn't able to build Deezloader remix via Docker but I had to install it directly on the machine. 

In case someone is having same issue.
