### ISSUE TITLE
Can't download large files

### ISSUE THREAD

**Issue by dappleapple** [RemixDev/DRemixIssues#30]
1 track in FLAC format is not downloaded. The download continues indefinitely, the file does not appear in the folder (in mp3 format, the download continues indefinitely, but the file appears in the folder). I guess because of the length of the track.
Is it possible to fix this?

1. Go to settings and change bitrate to FLAC 1411 kbps.
2. Go to search and find "Spring Tube vs. Release Records Progressive Classic (Continuous Mix)" song.
3. Click on download button.
4. Wait infinity...

 - OS: Win 10 x64
 - Version 1803

Log File
```
win32 - Windows_NT 10.0.17134 x64

[Info] Server is running @ localhost:1730
[Info] Connection received!
[Info] Checking for updates
[Info] Running the latest version!
[Info] Loading Personal Playlists
[Info] Loaded 2 Playlists
[Info] Loading Personal Playlists
[Info] Settings updated
[Info] Loaded 2 Playlists
[Info] Added to Queue 138590853
[Info] Registered track: 138590853:9 | Dj SlanG - Spring Tube vs. Release Records Progressive Classic (Continuous Mix)
[Info] [Dj SlanG - Spring Tube vs. Release Records Progressive Classic (Continuous Mix)] Getting album info
[Info] [Dj SlanG - Spring Tube vs. Release Records Progressive Classic (Continuous Mix)] Getting BPM
[Info] [Dj SlanG - Spring Tube vs. Release Records Progressive Classic (Continuous Mix)] Downloading file to C:\Users\Admin\Deezloader Music\Dj SlanG - Spring Tube vs. Release Records Progressive Classic (Continuous Mix).flac
[Info] [Dj SlanG - Spring Tube vs. Release Records Progressive Classic (Continuous Mix)] Cover already downloaded
[Info] [Dj SlanG - Spring Tube vs. Release Records Progressive Classic (Continuous Mix)] Starting the download process
[Info] [Dj SlanG - Spring Tube vs. Release Records Progressive Classic (Continuous Mix)] Downloading track
[Error] RangeError: Invalid string length
    at Array.join (native)
    at Request.<anonymous> (C:\Users\Admin\AppData\Local\Programs\Deezloader Remix\resources\app.asar\node_modules\request\request.js:1147:31)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\Users\Admin\AppData\Local\Programs\Deezloader Remix\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by RemixDev** [comment]
Fixed with pull request [427](https://notabug.org/RemixDevs/DeezloaderRemix/pulls/427)
