### ISSUE TITLE
Deezloader Remix 4.2.2 Black screen (EACCES 0.0.0.0:1730)

### ISSUE THREAD

**Issue by Titi66200** [RemixDev/DRemixIssues#34]
Windows 10 x64 1903 (18362.267).
Deezloader no longer launches.
log.
`win32 - Windows_NT 10.0.18362 x64

[Info] Server is running @ localhost:1730
[Error] Error: listen EACCES 0.0.0.0:1730
    at Server.setupListenHandle [as _listen2] (net.js:1313:19)
    at listenInCluster (net.js:1378:12)
    at Server.listen (net.js:1466:7)
    at Object.<anonymous> (C:\Program Files (Ext)\Deezloader\resources\app.asar\app.js:94:8)
    at Object.<anonymous> (C:\Program Files (Ext)\Deezloader\resources\app.asar\app.js:2382:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Program Files (Ext)\Deezloader\resources\app.asar\main.js:12:16)
    at Object.<anonymous> (C:\Program Files (Ext)\Deezloader\resources\app.asar\main.js:171:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Object.<anonymous> (C:\Program Files (Ext)\Deezloader\resources\electron.asar\browser\init.js:189:8)
    at Object.<anonymous> (C:\Program Files (Ext)\Deezloader\resources\electron.asar\browser\init.js:191:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
[Info] Settings updated`

Please Help.
Thanks

**Comment by RemixDev** [comment]
Try changing the port from 1730 to 2130 in config.json

**Comment by Titi66200** [comment]
Same thing with 2130 or 1930

**Comment by RemixDev** [comment]
Try with any number between 49152 and 65535

**Comment by Titi66200** [comment]
Thanks, works with 49152
