### ISSUE TITLE
queueDownload:album failed: TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by mekibe** [RemixDev/DRemixIssues#43]
[Error] queueDownload:album failed: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at fs.mkdirSync (fs.js:867:3)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:727:16)
    at queueDownload (C:\Program Files (x86)\DeezloaderRemix\resources\app\app.js:973:53)

**Comment by RemixDev** [comment]
Please follow the template to file a bug report
